# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b6f901c79855ec50b93a8970aef7b38ec2bd517786213e1ac79078ccd5e64abf3e17363c0289b6a84c9873986d0584f025b634ca2c97f8822d16536e723cd67

test:
  secret_key_base: 8add36b6c10c9d6dbb594b54453ce2571223183337287c406d3358f0246d7760abc3138dfb2dcfb2870a1d659e6383fb1044a9414a1e90d8e59ef2893aff308e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
